# ------- Branding Related Config ------- #
- name: INSTALLATION_NAME
  value: 'InHubFlow'
- name: LOGO_THUMBNAIL
  value: '/logo-icon.png'
- name: LOGO
  value: '/logo-master-light.png'
- name: LOGO_DARK
  value: '/logo-master-dark.png'
- name: BRAND_URL
  value: 'https://inhubflow.online'
- name: WIDGET_BRAND_URL
  value: 'https://inhubflow.online'
- name: BRAND_NAME
  value: 'InHubFlow'
- name: TERMS_URL
  value: 'https://inhubflow.online/terms'
- name: PRIVACY_URL
  value: 'https://inhubflow.online/privacy'
- name: DISPLAY_MANIFEST
  value: true
# ------- End of Branding Related Config ------- #
